# Generated by Django 3.2.9 on 2021-11-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_type', models.CharField(max_length=50)),
                ('pr_name', models.CharField(max_length=50)),
                ('pr_image', models.ImageField(upload_to='')),
                ('pr_price', models.FloatField()),
                ('pr_cals', models.IntegerField()),
                ('pr_energy', models.CharField(max_length=50)),
            ],
        ),
    ]
