# Generated by Django 3.2.9 on 2021-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('ex_name', models.CharField(max_length=50)),
                ('ex_cals', models.IntegerField()),
            ],
        ),
    ]
