# Generated by Django 3.2.9 on 2021-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0002_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='PT',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('pt_name', models.CharField(max_length=50)),
                ('pt_sex', models.CharField(max_length=50)),
                ('pt_age', models.IntegerField()),
                ('pt_exp', models.IntegerField()),
                ('pt_price', models.FloatField()),
            ],
        ),
    ]
