# Generated by Django 3.2.9 on 2021-11-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0003_pt'),
    ]

    operations = [
        migrations.CreateModel(
            name='whey',
            fields=[
                ('whey_id', models.AutoField(primary_key=True, serialize=False)),
                ('whey_name', models.CharField(max_length=50)),
                ('whey_price', models.FloatField()),
            ],
        ),
    ]
