# Generated by Django 3.2.9 on 2021-12-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0004_whey'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='ex_img',
            field=models.ImageField(default=-1.0, upload_to=''),
            preserve_default=False,
        ),
    ]
