# Generated by Django 3.2.9 on 2021-12-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0005_exercise_ex_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='ex_img',
        ),
    ]
