# Generated by Django 3.2.9 on 2021-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0007_exercise_ex_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='ex_img',
            field=models.ImageField(default='static/assets/img/ex/Hiit.png', upload_to='static/assets/img/ex/'),
        ),
    ]
