# Generated by Django 3.2.9 on 2021-12-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0008_alter_exercise_ex_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='whey',
            name='whey_img',
            field=models.ImageField(default='static/assets/img/whey/pic1.png', upload_to='static/assets/img/whey/'),
        ),
    ]
